# Generated by Django 4.2.2 on 2024-10-26 17:07

from django.db import migrations, models
import regcore.models


class Migration(migrations.Migration):

    dependencies = [
        ('regcore', '0004_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=regcore.models.recipe_image_file_path),
        ),
    ]
